// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetAmbientweatherStationMac sets provided value as "ambientweather.station.mac" attribute.
func (rb *ResourceBuilder) SetAmbientweatherStationMac(val string) {
	if rb.config.AmbientweatherStationMac.Enabled {
		rb.res.Attributes().PutStr("ambientweather.station.mac", val)
	}
}

// SetAmbientweatherStationName sets provided value as "ambientweather.station.name" attribute.
func (rb *ResourceBuilder) SetAmbientweatherStationName(val string) {
	if rb.config.AmbientweatherStationName.Enabled {
		rb.res.Attributes().PutStr("ambientweather.station.name", val)
	}
}

// SetAmbientweatherStationType sets provided value as "ambientweather.station.type" attribute.
func (rb *ResourceBuilder) SetAmbientweatherStationType(val string) {
	if rb.config.AmbientweatherStationType.Enabled {
		rb.res.Attributes().PutStr("ambientweather.station.type", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
