// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/ambientweather component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ambientweather")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ambientweatherreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
