// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["ambientweather.battery.status"] = mb.metricAmbientweatherBatteryStatus.config.AggregationStrategy
			aggMap["ambientweather.humidity"] = mb.metricAmbientweatherHumidity.config.AggregationStrategy
			aggMap["ambientweather.lightning.strikes"] = mb.metricAmbientweatherLightningStrikes.config.AggregationStrategy
			aggMap["ambientweather.pm25"] = mb.metricAmbientweatherPm25.config.AggregationStrategy
			aggMap["ambientweather.rainfall"] = mb.metricAmbientweatherRainfall.config.AggregationStrategy
			aggMap["ambientweather.soil.moisture"] = mb.metricAmbientweatherSoilMoisture.config.AggregationStrategy
			aggMap["ambientweather.temperature"] = mb.metricAmbientweatherTemperature.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherBatteryStatusDataPoint(ts, 1, "sensor-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherBatteryStatusDataPoint(ts, 3, "sensor-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherHumidityDataPoint(ts, 1, "sensor-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherHumidityDataPoint(ts, 3, "sensor-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherLightningDistanceDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherLightningStrikesDataPoint(ts, 1, "lightning.period-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherLightningStrikesDataPoint(ts, 3, "lightning.period-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherPm25DataPoint(ts, 1, "sensor-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherPm25DataPoint(ts, 3, "sensor-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherPressureAbsoluteDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherPressureRelativeDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherRainRateDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherRainfallDataPoint(ts, 1, "rainfall.period-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherRainfallDataPoint(ts, 3, "rainfall.period-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherSoilMoistureDataPoint(ts, 1, "sensor-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherSoilMoistureDataPoint(ts, 3, "sensor-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherSolarRadiationDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherTemperatureDataPoint(ts, 1, "sensor-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAmbientweatherTemperatureDataPoint(ts, 3, "sensor-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherUvIndexDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherWindDirectionDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherWindGustDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAmbientweatherWindSpeedDataPoint(ts, 1)

			rb := mb.NewResourceBuilder()
			rb.SetAmbientweatherStationMac("ambientweather.station.mac-val")
			rb.SetAmbientweatherStationName("ambientweather.station.name-val")
			rb.SetAmbientweatherStationType("ambientweather.station.type-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricAmbientweatherBatteryStatus.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherHumidity.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherLightningStrikes.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherPm25.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherRainfall.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherSoilMoisture.aggDataPoints)
				assert.Empty(t, mb.metricAmbientweatherTemperature.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "ambientweather.battery.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.battery.status"], "Found a duplicate in the metrics slice: ambientweather.battery.status")
						validatedMetrics["ambientweather.battery.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Battery status reported by a sensor: 1 = OK, 0 = low.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						sensorAttrVal, ok := dp.Attributes().Get("sensor")
						assert.True(t, ok)
						assert.Equal(t, "sensor-val", sensorAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.battery.status"], "Found a duplicate in the metrics slice: ambientweather.battery.status")
						validatedMetrics["ambientweather.battery.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Battery status reported by a sensor: 1 = OK, 0 = low.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["ambientweather.battery.status"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("sensor")
						assert.False(t, ok)
					}
				case "ambientweather.humidity":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.humidity"], "Found a duplicate in the metrics slice: ambientweather.humidity")
						validatedMetrics["ambientweather.humidity"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Relative humidity.", mi.Description())
						assert.Equal(t, "%", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						sensorAttrVal, ok := dp.Attributes().Get("sensor")
						assert.True(t, ok)
						assert.Equal(t, "sensor-val", sensorAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.humidity"], "Found a duplicate in the metrics slice: ambientweather.humidity")
						validatedMetrics["ambientweather.humidity"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Relative humidity.", mi.Description())
						assert.Equal(t, "%", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["ambientweather.humidity"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("sensor")
						assert.False(t, ok)
					}
				case "ambientweather.lightning.distance":
					assert.False(t, validatedMetrics["ambientweather.lightning.distance"], "Found a duplicate in the metrics slice: ambientweather.lightning.distance")
					validatedMetrics["ambientweather.lightning.distance"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Distance to the last detected lightning strike. Reported in km on consoles configured with metric wind-speed units.", mi.Description())
					assert.Equal(t, "km", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.lightning.strikes":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.lightning.strikes"], "Found a duplicate in the metrics slice: ambientweather.lightning.strikes")
						validatedMetrics["ambientweather.lightning.strikes"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Lightning strikes counted by the device over the reported period.", mi.Description())
						assert.Equal(t, "{strike}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						lightningPeriodAttrVal, ok := dp.Attributes().Get("lightning.period")
						assert.True(t, ok)
						assert.Equal(t, "lightning.period-val", lightningPeriodAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.lightning.strikes"], "Found a duplicate in the metrics slice: ambientweather.lightning.strikes")
						validatedMetrics["ambientweather.lightning.strikes"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Lightning strikes counted by the device over the reported period.", mi.Description())
						assert.Equal(t, "{strike}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["ambientweather.lightning.strikes"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("lightning.period")
						assert.False(t, ok)
					}
				case "ambientweather.pm25":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.pm25"], "Found a duplicate in the metrics slice: ambientweather.pm25")
						validatedMetrics["ambientweather.pm25"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "PM2.5 particulate-matter mass concentration.", mi.Description())
						assert.Equal(t, "ug/m3", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						sensorAttrVal, ok := dp.Attributes().Get("sensor")
						assert.True(t, ok)
						assert.Equal(t, "sensor-val", sensorAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.pm25"], "Found a duplicate in the metrics slice: ambientweather.pm25")
						validatedMetrics["ambientweather.pm25"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "PM2.5 particulate-matter mass concentration.", mi.Description())
						assert.Equal(t, "ug/m3", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["ambientweather.pm25"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("sensor")
						assert.False(t, ok)
					}
				case "ambientweather.pressure.absolute":
					assert.False(t, validatedMetrics["ambientweather.pressure.absolute"], "Found a duplicate in the metrics slice: ambientweather.pressure.absolute")
					validatedMetrics["ambientweather.pressure.absolute"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Absolute (station) barometric pressure.", mi.Description())
					assert.Equal(t, "hPa", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.pressure.relative":
					assert.False(t, validatedMetrics["ambientweather.pressure.relative"], "Found a duplicate in the metrics slice: ambientweather.pressure.relative")
					validatedMetrics["ambientweather.pressure.relative"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Relative (sea-level-adjusted) barometric pressure.", mi.Description())
					assert.Equal(t, "hPa", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.rain.rate":
					assert.False(t, validatedMetrics["ambientweather.rain.rate"], "Found a duplicate in the metrics slice: ambientweather.rain.rate")
					validatedMetrics["ambientweather.rain.rate"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Instantaneous rain rate.", mi.Description())
					assert.Equal(t, "mm/h", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.rainfall":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.rainfall"], "Found a duplicate in the metrics slice: ambientweather.rainfall")
						validatedMetrics["ambientweather.rainfall"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Accumulated rainfall over the reported period.", mi.Description())
						assert.Equal(t, "mm", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						rainfallPeriodAttrVal, ok := dp.Attributes().Get("rainfall.period")
						assert.True(t, ok)
						assert.Equal(t, "rainfall.period-val", rainfallPeriodAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.rainfall"], "Found a duplicate in the metrics slice: ambientweather.rainfall")
						validatedMetrics["ambientweather.rainfall"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Accumulated rainfall over the reported period.", mi.Description())
						assert.Equal(t, "mm", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["ambientweather.rainfall"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("rainfall.period")
						assert.False(t, ok)
					}
				case "ambientweather.soil.moisture":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.soil.moisture"], "Found a duplicate in the metrics slice: ambientweather.soil.moisture")
						validatedMetrics["ambientweather.soil.moisture"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Soil moisture.", mi.Description())
						assert.Equal(t, "%", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						sensorAttrVal, ok := dp.Attributes().Get("sensor")
						assert.True(t, ok)
						assert.Equal(t, "sensor-val", sensorAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.soil.moisture"], "Found a duplicate in the metrics slice: ambientweather.soil.moisture")
						validatedMetrics["ambientweather.soil.moisture"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Soil moisture.", mi.Description())
						assert.Equal(t, "%", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["ambientweather.soil.moisture"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("sensor")
						assert.False(t, ok)
					}
				case "ambientweather.solar.radiation":
					assert.False(t, validatedMetrics["ambientweather.solar.radiation"], "Found a duplicate in the metrics slice: ambientweather.solar.radiation")
					validatedMetrics["ambientweather.solar.radiation"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Solar irradiance.", mi.Description())
					assert.Equal(t, "W/m2", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.temperature":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["ambientweather.temperature"], "Found a duplicate in the metrics slice: ambientweather.temperature")
						validatedMetrics["ambientweather.temperature"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Air temperature reading.", mi.Description())
						assert.Equal(t, "Cel", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						sensorAttrVal, ok := dp.Attributes().Get("sensor")
						assert.True(t, ok)
						assert.Equal(t, "sensor-val", sensorAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["ambientweather.temperature"], "Found a duplicate in the metrics slice: ambientweather.temperature")
						validatedMetrics["ambientweather.temperature"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Air temperature reading.", mi.Description())
						assert.Equal(t, "Cel", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["ambientweather.temperature"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("sensor")
						assert.False(t, ok)
					}
				case "ambientweather.uv.index":
					assert.False(t, validatedMetrics["ambientweather.uv.index"], "Found a duplicate in the metrics slice: ambientweather.uv.index")
					validatedMetrics["ambientweather.uv.index"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Ultraviolet radiation index.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "ambientweather.wind.direction":
					assert.False(t, validatedMetrics["ambientweather.wind.direction"], "Found a duplicate in the metrics slice: ambientweather.wind.direction")
					validatedMetrics["ambientweather.wind.direction"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Wind direction, in degrees clockwise from true north.", mi.Description())
					assert.Equal(t, "deg", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.wind.gust":
					assert.False(t, validatedMetrics["ambientweather.wind.gust"], "Found a duplicate in the metrics slice: ambientweather.wind.gust")
					validatedMetrics["ambientweather.wind.gust"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Instantaneous wind gust speed.", mi.Description())
					assert.Equal(t, "m/s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "ambientweather.wind.speed":
					assert.False(t, validatedMetrics["ambientweather.wind.speed"], "Found a duplicate in the metrics slice: ambientweather.wind.speed")
					validatedMetrics["ambientweather.wind.speed"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Instantaneous wind speed.", mi.Description())
					assert.Equal(t, "m/s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				}
			}
		})
	}
}
