// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetAmbientweatherStationMac("ambientweather.station.mac-val")
			rb.SetAmbientweatherStationName("ambientweather.station.name-val")
			rb.SetAmbientweatherStationType("ambientweather.station.type-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 3, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 3, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}
			ambientweatherStationMacAttrVal, ok := res.Attributes().Get("ambientweather.station.mac")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ambientweather.station.mac-val", ambientweatherStationMacAttrVal.Str())
			}
			ambientweatherStationNameAttrVal, ok := res.Attributes().Get("ambientweather.station.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ambientweather.station.name-val", ambientweatherStationNameAttrVal.Str())
			}
			ambientweatherStationTypeAttrVal, ok := res.Attributes().Get("ambientweather.station.type")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "ambientweather.station.type-val", ambientweatherStationTypeAttrVal.Str())
			}
		})
	}
}
