// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// AmbientweatherBatteryStatusMetricAttributeKey specifies the key of an attribute for the ambientweather.battery.status metric.
type AmbientweatherBatteryStatusMetricAttributeKey string

const (
	AmbientweatherBatteryStatusMetricAttributeKeySensor AmbientweatherBatteryStatusMetricAttributeKey = "sensor"
)

// AmbientweatherBatteryStatusMetricConfig provides config for the ambientweather.battery.status metric.
type AmbientweatherBatteryStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherBatteryStatusMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherBatteryStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherBatteryStatusMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherBatteryStatusMetricAttributeKeySensor:
		default:
			return fmt.Errorf("metric ambientweather.battery.status doesn't have an attribute %v, valid attributes: [sensor]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherHumidityMetricAttributeKey specifies the key of an attribute for the ambientweather.humidity metric.
type AmbientweatherHumidityMetricAttributeKey string

const (
	AmbientweatherHumidityMetricAttributeKeySensor AmbientweatherHumidityMetricAttributeKey = "sensor"
)

// AmbientweatherHumidityMetricConfig provides config for the ambientweather.humidity metric.
type AmbientweatherHumidityMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherHumidityMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherHumidityMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherHumidityMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherHumidityMetricAttributeKeySensor:
		default:
			return fmt.Errorf("metric ambientweather.humidity doesn't have an attribute %v, valid attributes: [sensor]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherLightningDistanceMetricConfig provides config for the ambientweather.lightning.distance metric.
type AmbientweatherLightningDistanceMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherLightningDistanceMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherLightningStrikesMetricAttributeKey specifies the key of an attribute for the ambientweather.lightning.strikes metric.
type AmbientweatherLightningStrikesMetricAttributeKey string

const (
	AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod AmbientweatherLightningStrikesMetricAttributeKey = "lightning.period"
)

// AmbientweatherLightningStrikesMetricConfig provides config for the ambientweather.lightning.strikes metric.
type AmbientweatherLightningStrikesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherLightningStrikesMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherLightningStrikesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherLightningStrikesMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod:
		default:
			return fmt.Errorf("metric ambientweather.lightning.strikes doesn't have an attribute %v, valid attributes: [lightning.period]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherPm25MetricAttributeKey specifies the key of an attribute for the ambientweather.pm25 metric.
type AmbientweatherPm25MetricAttributeKey string

const (
	AmbientweatherPm25MetricAttributeKeySensor AmbientweatherPm25MetricAttributeKey = "sensor"
)

// AmbientweatherPm25MetricConfig provides config for the ambientweather.pm25 metric.
type AmbientweatherPm25MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherPm25MetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherPm25MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherPm25MetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherPm25MetricAttributeKeySensor:
		default:
			return fmt.Errorf("metric ambientweather.pm25 doesn't have an attribute %v, valid attributes: [sensor]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherPressureAbsoluteMetricConfig provides config for the ambientweather.pressure.absolute metric.
type AmbientweatherPressureAbsoluteMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherPressureAbsoluteMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherPressureRelativeMetricConfig provides config for the ambientweather.pressure.relative metric.
type AmbientweatherPressureRelativeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherPressureRelativeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherRainRateMetricConfig provides config for the ambientweather.rain.rate metric.
type AmbientweatherRainRateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherRainRateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherRainfallMetricAttributeKey specifies the key of an attribute for the ambientweather.rainfall metric.
type AmbientweatherRainfallMetricAttributeKey string

const (
	AmbientweatherRainfallMetricAttributeKeyRainfallPeriod AmbientweatherRainfallMetricAttributeKey = "rainfall.period"
)

// AmbientweatherRainfallMetricConfig provides config for the ambientweather.rainfall metric.
type AmbientweatherRainfallMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherRainfallMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherRainfallMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherRainfallMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherRainfallMetricAttributeKeyRainfallPeriod:
		default:
			return fmt.Errorf("metric ambientweather.rainfall doesn't have an attribute %v, valid attributes: [rainfall.period]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherSoilMoistureMetricAttributeKey specifies the key of an attribute for the ambientweather.soil.moisture metric.
type AmbientweatherSoilMoistureMetricAttributeKey string

const (
	AmbientweatherSoilMoistureMetricAttributeKeySensor AmbientweatherSoilMoistureMetricAttributeKey = "sensor"
)

// AmbientweatherSoilMoistureMetricConfig provides config for the ambientweather.soil.moisture metric.
type AmbientweatherSoilMoistureMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                         `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherSoilMoistureMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherSoilMoistureMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherSoilMoistureMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherSoilMoistureMetricAttributeKeySensor:
		default:
			return fmt.Errorf("metric ambientweather.soil.moisture doesn't have an attribute %v, valid attributes: [sensor]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherSolarRadiationMetricConfig provides config for the ambientweather.solar.radiation metric.
type AmbientweatherSolarRadiationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherSolarRadiationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherTemperatureMetricAttributeKey specifies the key of an attribute for the ambientweather.temperature metric.
type AmbientweatherTemperatureMetricAttributeKey string

const (
	AmbientweatherTemperatureMetricAttributeKeySensor AmbientweatherTemperatureMetricAttributeKey = "sensor"
)

// AmbientweatherTemperatureMetricConfig provides config for the ambientweather.temperature metric.
type AmbientweatherTemperatureMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AmbientweatherTemperatureMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AmbientweatherTemperatureMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *AmbientweatherTemperatureMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case AmbientweatherTemperatureMetricAttributeKeySensor:
		default:
			return fmt.Errorf("metric ambientweather.temperature doesn't have an attribute %v, valid attributes: [sensor]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// AmbientweatherUvIndexMetricConfig provides config for the ambientweather.uv.index metric.
type AmbientweatherUvIndexMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherUvIndexMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherWindDirectionMetricConfig provides config for the ambientweather.wind.direction metric.
type AmbientweatherWindDirectionMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherWindDirectionMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherWindGustMetricConfig provides config for the ambientweather.wind.gust metric.
type AmbientweatherWindGustMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherWindGustMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AmbientweatherWindSpeedMetricConfig provides config for the ambientweather.wind.speed metric.
type AmbientweatherWindSpeedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AmbientweatherWindSpeedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for ambientweather metrics.
type MetricsConfig struct {
	AmbientweatherBatteryStatus     AmbientweatherBatteryStatusMetricConfig     `mapstructure:"ambientweather.battery.status"`
	AmbientweatherHumidity          AmbientweatherHumidityMetricConfig          `mapstructure:"ambientweather.humidity"`
	AmbientweatherLightningDistance AmbientweatherLightningDistanceMetricConfig `mapstructure:"ambientweather.lightning.distance"`
	AmbientweatherLightningStrikes  AmbientweatherLightningStrikesMetricConfig  `mapstructure:"ambientweather.lightning.strikes"`
	AmbientweatherPm25              AmbientweatherPm25MetricConfig              `mapstructure:"ambientweather.pm25"`
	AmbientweatherPressureAbsolute  AmbientweatherPressureAbsoluteMetricConfig  `mapstructure:"ambientweather.pressure.absolute"`
	AmbientweatherPressureRelative  AmbientweatherPressureRelativeMetricConfig  `mapstructure:"ambientweather.pressure.relative"`
	AmbientweatherRainRate          AmbientweatherRainRateMetricConfig          `mapstructure:"ambientweather.rain.rate"`
	AmbientweatherRainfall          AmbientweatherRainfallMetricConfig          `mapstructure:"ambientweather.rainfall"`
	AmbientweatherSoilMoisture      AmbientweatherSoilMoistureMetricConfig      `mapstructure:"ambientweather.soil.moisture"`
	AmbientweatherSolarRadiation    AmbientweatherSolarRadiationMetricConfig    `mapstructure:"ambientweather.solar.radiation"`
	AmbientweatherTemperature       AmbientweatherTemperatureMetricConfig       `mapstructure:"ambientweather.temperature"`
	AmbientweatherUvIndex           AmbientweatherUvIndexMetricConfig           `mapstructure:"ambientweather.uv.index"`
	AmbientweatherWindDirection     AmbientweatherWindDirectionMetricConfig     `mapstructure:"ambientweather.wind.direction"`
	AmbientweatherWindGust          AmbientweatherWindGustMetricConfig          `mapstructure:"ambientweather.wind.gust"`
	AmbientweatherWindSpeed         AmbientweatherWindSpeedMetricConfig         `mapstructure:"ambientweather.wind.speed"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		AmbientweatherBatteryStatus: AmbientweatherBatteryStatusMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherBatteryStatusMetricAttributeKey{AmbientweatherBatteryStatusMetricAttributeKeySensor},
		},
		AmbientweatherHumidity: AmbientweatherHumidityMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherHumidityMetricAttributeKey{AmbientweatherHumidityMetricAttributeKeySensor},
		},
		AmbientweatherLightningDistance: AmbientweatherLightningDistanceMetricConfig{
			Enabled: true,
		},
		AmbientweatherLightningStrikes: AmbientweatherLightningStrikesMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherLightningStrikesMetricAttributeKey{AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod},
		},
		AmbientweatherPm25: AmbientweatherPm25MetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherPm25MetricAttributeKey{AmbientweatherPm25MetricAttributeKeySensor},
		},
		AmbientweatherPressureAbsolute: AmbientweatherPressureAbsoluteMetricConfig{
			Enabled: true,
		},
		AmbientweatherPressureRelative: AmbientweatherPressureRelativeMetricConfig{
			Enabled: true,
		},
		AmbientweatherRainRate: AmbientweatherRainRateMetricConfig{
			Enabled: true,
		},
		AmbientweatherRainfall: AmbientweatherRainfallMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherRainfallMetricAttributeKey{AmbientweatherRainfallMetricAttributeKeyRainfallPeriod},
		},
		AmbientweatherSoilMoisture: AmbientweatherSoilMoistureMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherSoilMoistureMetricAttributeKey{AmbientweatherSoilMoistureMetricAttributeKeySensor},
		},
		AmbientweatherSolarRadiation: AmbientweatherSolarRadiationMetricConfig{
			Enabled: true,
		},
		AmbientweatherTemperature: AmbientweatherTemperatureMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []AmbientweatherTemperatureMetricAttributeKey{AmbientweatherTemperatureMetricAttributeKeySensor},
		},
		AmbientweatherUvIndex: AmbientweatherUvIndexMetricConfig{
			Enabled: true,
		},
		AmbientweatherWindDirection: AmbientweatherWindDirectionMetricConfig{
			Enabled: true,
		},
		AmbientweatherWindGust: AmbientweatherWindGustMetricConfig{
			Enabled: true,
		},
		AmbientweatherWindSpeed: AmbientweatherWindSpeedMetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for ambientweather resource attributes.
type ResourceAttributesConfig struct {
	AmbientweatherStationMac  ResourceAttributeConfig `mapstructure:"ambientweather.station.mac"`
	AmbientweatherStationName ResourceAttributeConfig `mapstructure:"ambientweather.station.name"`
	AmbientweatherStationType ResourceAttributeConfig `mapstructure:"ambientweather.station.type"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		AmbientweatherStationMac: ResourceAttributeConfig{
			Enabled: true,
		},
		AmbientweatherStationName: ResourceAttributeConfig{
			Enabled: true,
		},
		AmbientweatherStationType: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for ambientweather metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
