// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					AmbientweatherBatteryStatus: AmbientweatherBatteryStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherBatteryStatusMetricAttributeKey{AmbientweatherBatteryStatusMetricAttributeKeySensor},
					},
					AmbientweatherHumidity: AmbientweatherHumidityMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherHumidityMetricAttributeKey{AmbientweatherHumidityMetricAttributeKeySensor},
					},
					AmbientweatherLightningDistance: AmbientweatherLightningDistanceMetricConfig{
						Enabled: true,
					},
					AmbientweatherLightningStrikes: AmbientweatherLightningStrikesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherLightningStrikesMetricAttributeKey{AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod},
					},
					AmbientweatherPm25: AmbientweatherPm25MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherPm25MetricAttributeKey{AmbientweatherPm25MetricAttributeKeySensor},
					},
					AmbientweatherPressureAbsolute: AmbientweatherPressureAbsoluteMetricConfig{
						Enabled: true,
					},
					AmbientweatherPressureRelative: AmbientweatherPressureRelativeMetricConfig{
						Enabled: true,
					},
					AmbientweatherRainRate: AmbientweatherRainRateMetricConfig{
						Enabled: true,
					},
					AmbientweatherRainfall: AmbientweatherRainfallMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherRainfallMetricAttributeKey{AmbientweatherRainfallMetricAttributeKeyRainfallPeriod},
					},
					AmbientweatherSoilMoisture: AmbientweatherSoilMoistureMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherSoilMoistureMetricAttributeKey{AmbientweatherSoilMoistureMetricAttributeKeySensor},
					},
					AmbientweatherSolarRadiation: AmbientweatherSolarRadiationMetricConfig{
						Enabled: true,
					},
					AmbientweatherTemperature: AmbientweatherTemperatureMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherTemperatureMetricAttributeKey{AmbientweatherTemperatureMetricAttributeKeySensor},
					},
					AmbientweatherUvIndex: AmbientweatherUvIndexMetricConfig{
						Enabled: true,
					},
					AmbientweatherWindDirection: AmbientweatherWindDirectionMetricConfig{
						Enabled: true,
					},
					AmbientweatherWindGust: AmbientweatherWindGustMetricConfig{
						Enabled: true,
					},
					AmbientweatherWindSpeed: AmbientweatherWindSpeedMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					AmbientweatherStationMac:  ResourceAttributeConfig{Enabled: true},
					AmbientweatherStationName: ResourceAttributeConfig{Enabled: true},
					AmbientweatherStationType: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					AmbientweatherBatteryStatus: AmbientweatherBatteryStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherBatteryStatusMetricAttributeKey{AmbientweatherBatteryStatusMetricAttributeKeySensor},
					},
					AmbientweatherHumidity: AmbientweatherHumidityMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherHumidityMetricAttributeKey{AmbientweatherHumidityMetricAttributeKeySensor},
					},
					AmbientweatherLightningDistance: AmbientweatherLightningDistanceMetricConfig{
						Enabled: false,
					},
					AmbientweatherLightningStrikes: AmbientweatherLightningStrikesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherLightningStrikesMetricAttributeKey{AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod},
					},
					AmbientweatherPm25: AmbientweatherPm25MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherPm25MetricAttributeKey{AmbientweatherPm25MetricAttributeKeySensor},
					},
					AmbientweatherPressureAbsolute: AmbientweatherPressureAbsoluteMetricConfig{
						Enabled: false,
					},
					AmbientweatherPressureRelative: AmbientweatherPressureRelativeMetricConfig{
						Enabled: false,
					},
					AmbientweatherRainRate: AmbientweatherRainRateMetricConfig{
						Enabled: false,
					},
					AmbientweatherRainfall: AmbientweatherRainfallMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherRainfallMetricAttributeKey{AmbientweatherRainfallMetricAttributeKeyRainfallPeriod},
					},
					AmbientweatherSoilMoisture: AmbientweatherSoilMoistureMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherSoilMoistureMetricAttributeKey{AmbientweatherSoilMoistureMetricAttributeKeySensor},
					},
					AmbientweatherSolarRadiation: AmbientweatherSolarRadiationMetricConfig{
						Enabled: false,
					},
					AmbientweatherTemperature: AmbientweatherTemperatureMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AmbientweatherTemperatureMetricAttributeKey{AmbientweatherTemperatureMetricAttributeKeySensor},
					},
					AmbientweatherUvIndex: AmbientweatherUvIndexMetricConfig{
						Enabled: false,
					},
					AmbientweatherWindDirection: AmbientweatherWindDirectionMetricConfig{
						Enabled: false,
					},
					AmbientweatherWindGust: AmbientweatherWindGustMetricConfig{
						Enabled: false,
					},
					AmbientweatherWindSpeed: AmbientweatherWindSpeedMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					AmbientweatherStationMac:  ResourceAttributeConfig{Enabled: false},
					AmbientweatherStationName: ResourceAttributeConfig{Enabled: false},
					AmbientweatherStationType: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(AmbientweatherBatteryStatusMetricConfig{}, AmbientweatherHumidityMetricConfig{}, AmbientweatherLightningDistanceMetricConfig{}, AmbientweatherLightningStrikesMetricConfig{}, AmbientweatherPm25MetricConfig{}, AmbientweatherPressureAbsoluteMetricConfig{}, AmbientweatherPressureRelativeMetricConfig{}, AmbientweatherRainRateMetricConfig{}, AmbientweatherRainfallMetricConfig{}, AmbientweatherSoilMoistureMetricConfig{}, AmbientweatherSolarRadiationMetricConfig{}, AmbientweatherTemperatureMetricConfig{}, AmbientweatherUvIndexMetricConfig{}, AmbientweatherWindDirectionMetricConfig{}, AmbientweatherWindGustMetricConfig{}, AmbientweatherWindSpeedMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestAmbientweatherBatteryStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherBatteryStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherBatteryStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.battery.status doesn't have an attribute invalid, valid attributes: [sensor]")

	cfg = DefaultMetricsConfig().AmbientweatherBatteryStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherHumidityMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherHumidity
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherHumidityMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.humidity doesn't have an attribute invalid, valid attributes: [sensor]")

	cfg = DefaultMetricsConfig().AmbientweatherHumidity
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherLightningStrikesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherLightningStrikes
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherLightningStrikesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.lightning.strikes doesn't have an attribute invalid, valid attributes: [lightning.period]")

	cfg = DefaultMetricsConfig().AmbientweatherLightningStrikes
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherPm25MetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherPm25
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherPm25MetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.pm25 doesn't have an attribute invalid, valid attributes: [sensor]")

	cfg = DefaultMetricsConfig().AmbientweatherPm25
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherRainfallMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherRainfall
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherRainfallMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.rainfall doesn't have an attribute invalid, valid attributes: [rainfall.period]")

	cfg = DefaultMetricsConfig().AmbientweatherRainfall
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherSoilMoistureMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherSoilMoisture
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherSoilMoistureMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.soil.moisture doesn't have an attribute invalid, valid attributes: [sensor]")

	cfg = DefaultMetricsConfig().AmbientweatherSoilMoisture
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAmbientweatherTemperatureMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AmbientweatherTemperature
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AmbientweatherTemperatureMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric ambientweather.temperature doesn't have an attribute invalid, valid attributes: [sensor]")

	cfg = DefaultMetricsConfig().AmbientweatherTemperature
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				AmbientweatherStationMac:  ResourceAttributeConfig{Enabled: true},
				AmbientweatherStationName: ResourceAttributeConfig{Enabled: true},
				AmbientweatherStationType: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				AmbientweatherStationMac:  ResourceAttributeConfig{Enabled: false},
				AmbientweatherStationName: ResourceAttributeConfig{Enabled: false},
				AmbientweatherStationType: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
