// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"slices"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	AmbientweatherBatteryStatus: metricInfo{
		Name:       "ambientweather.battery.status",
		Attributes: []string{"sensor"},
	},
	AmbientweatherHumidity: metricInfo{
		Name:       "ambientweather.humidity",
		Attributes: []string{"sensor"},
	},
	AmbientweatherLightningDistance: metricInfo{
		Name: "ambientweather.lightning.distance",
	},
	AmbientweatherLightningStrikes: metricInfo{
		Name:       "ambientweather.lightning.strikes",
		Attributes: []string{"lightning.period"},
	},
	AmbientweatherPm25: metricInfo{
		Name:       "ambientweather.pm25",
		Attributes: []string{"sensor"},
	},
	AmbientweatherPressureAbsolute: metricInfo{
		Name: "ambientweather.pressure.absolute",
	},
	AmbientweatherPressureRelative: metricInfo{
		Name: "ambientweather.pressure.relative",
	},
	AmbientweatherRainRate: metricInfo{
		Name: "ambientweather.rain.rate",
	},
	AmbientweatherRainfall: metricInfo{
		Name:       "ambientweather.rainfall",
		Attributes: []string{"rainfall.period"},
	},
	AmbientweatherSoilMoisture: metricInfo{
		Name:       "ambientweather.soil.moisture",
		Attributes: []string{"sensor"},
	},
	AmbientweatherSolarRadiation: metricInfo{
		Name: "ambientweather.solar.radiation",
	},
	AmbientweatherTemperature: metricInfo{
		Name:       "ambientweather.temperature",
		Attributes: []string{"sensor"},
	},
	AmbientweatherUvIndex: metricInfo{
		Name: "ambientweather.uv.index",
	},
	AmbientweatherWindDirection: metricInfo{
		Name: "ambientweather.wind.direction",
	},
	AmbientweatherWindGust: metricInfo{
		Name: "ambientweather.wind.gust",
	},
	AmbientweatherWindSpeed: metricInfo{
		Name: "ambientweather.wind.speed",
	},
}

type metricsInfo struct {
	AmbientweatherBatteryStatus     metricInfo
	AmbientweatherHumidity          metricInfo
	AmbientweatherLightningDistance metricInfo
	AmbientweatherLightningStrikes  metricInfo
	AmbientweatherPm25              metricInfo
	AmbientweatherPressureAbsolute  metricInfo
	AmbientweatherPressureRelative  metricInfo
	AmbientweatherRainRate          metricInfo
	AmbientweatherRainfall          metricInfo
	AmbientweatherSoilMoisture      metricInfo
	AmbientweatherSolarRadiation    metricInfo
	AmbientweatherTemperature       metricInfo
	AmbientweatherUvIndex           metricInfo
	AmbientweatherWindDirection     metricInfo
	AmbientweatherWindGust          metricInfo
	AmbientweatherWindSpeed         metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricAmbientweatherBatteryStatus struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        AmbientweatherBatteryStatusMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []int64                                 // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.battery.status metric with initial data.
func (m *metricAmbientweatherBatteryStatus) init() {
	m.data.SetName("ambientweather.battery.status")
	m.data.SetDescription("Battery status reported by a sensor: 1 = OK, 0 = low.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherBatteryStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, sensorAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherBatteryStatusMetricAttributeKeySensor) {
		dp.Attributes().PutStr("sensor", sensorAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherBatteryStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherBatteryStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherBatteryStatus(cfg AmbientweatherBatteryStatusMetricConfig) metricAmbientweatherBatteryStatus {
	m := metricAmbientweatherBatteryStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherHumidity struct {
	data          pmetric.Metric                     // data buffer for generated metric.
	config        AmbientweatherHumidityMetricConfig // metric config provided by user.
	capacity      int                                // max observed number of data points added to the metric.
	aggDataPoints []float64                          // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.humidity metric with initial data.
func (m *metricAmbientweatherHumidity) init() {
	m.data.SetName("ambientweather.humidity")
	m.data.SetDescription("Relative humidity.")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherHumidity) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherHumidityMetricAttributeKeySensor) {
		dp.Attributes().PutStr("sensor", sensorAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherHumidity) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherHumidity) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherHumidity(cfg AmbientweatherHumidityMetricConfig) metricAmbientweatherHumidity {
	m := metricAmbientweatherHumidity{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherLightningDistance struct {
	data     pmetric.Metric                              // data buffer for generated metric.
	config   AmbientweatherLightningDistanceMetricConfig // metric config provided by user.
	capacity int                                         // max observed number of data points added to the metric.
}

// init fills ambientweather.lightning.distance metric with initial data.
func (m *metricAmbientweatherLightningDistance) init() {
	m.data.SetName("ambientweather.lightning.distance")
	m.data.SetDescription("Distance to the last detected lightning strike. Reported in km on consoles configured with metric wind-speed units.")
	m.data.SetUnit("km")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherLightningDistance) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherLightningDistance) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherLightningDistance) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherLightningDistance(cfg AmbientweatherLightningDistanceMetricConfig) metricAmbientweatherLightningDistance {
	m := metricAmbientweatherLightningDistance{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherLightningStrikes struct {
	data          pmetric.Metric                             // data buffer for generated metric.
	config        AmbientweatherLightningStrikesMetricConfig // metric config provided by user.
	capacity      int                                        // max observed number of data points added to the metric.
	aggDataPoints []int64                                    // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.lightning.strikes metric with initial data.
func (m *metricAmbientweatherLightningStrikes) init() {
	m.data.SetName("ambientweather.lightning.strikes")
	m.data.SetDescription("Lightning strikes counted by the device over the reported period.")
	m.data.SetUnit("{strike}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherLightningStrikes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, lightningPeriodAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherLightningStrikesMetricAttributeKeyLightningPeriod) {
		dp.Attributes().PutStr("lightning.period", lightningPeriodAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherLightningStrikes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherLightningStrikes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherLightningStrikes(cfg AmbientweatherLightningStrikesMetricConfig) metricAmbientweatherLightningStrikes {
	m := metricAmbientweatherLightningStrikes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherPm25 struct {
	data          pmetric.Metric                 // data buffer for generated metric.
	config        AmbientweatherPm25MetricConfig // metric config provided by user.
	capacity      int                            // max observed number of data points added to the metric.
	aggDataPoints []float64                      // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.pm25 metric with initial data.
func (m *metricAmbientweatherPm25) init() {
	m.data.SetName("ambientweather.pm25")
	m.data.SetDescription("PM2.5 particulate-matter mass concentration.")
	m.data.SetUnit("ug/m3")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherPm25) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherPm25MetricAttributeKeySensor) {
		dp.Attributes().PutStr("sensor", sensorAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherPm25) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherPm25) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherPm25(cfg AmbientweatherPm25MetricConfig) metricAmbientweatherPm25 {
	m := metricAmbientweatherPm25{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherPressureAbsolute struct {
	data     pmetric.Metric                             // data buffer for generated metric.
	config   AmbientweatherPressureAbsoluteMetricConfig // metric config provided by user.
	capacity int                                        // max observed number of data points added to the metric.
}

// init fills ambientweather.pressure.absolute metric with initial data.
func (m *metricAmbientweatherPressureAbsolute) init() {
	m.data.SetName("ambientweather.pressure.absolute")
	m.data.SetDescription("Absolute (station) barometric pressure.")
	m.data.SetUnit("hPa")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherPressureAbsolute) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherPressureAbsolute) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherPressureAbsolute) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherPressureAbsolute(cfg AmbientweatherPressureAbsoluteMetricConfig) metricAmbientweatherPressureAbsolute {
	m := metricAmbientweatherPressureAbsolute{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherPressureRelative struct {
	data     pmetric.Metric                             // data buffer for generated metric.
	config   AmbientweatherPressureRelativeMetricConfig // metric config provided by user.
	capacity int                                        // max observed number of data points added to the metric.
}

// init fills ambientweather.pressure.relative metric with initial data.
func (m *metricAmbientweatherPressureRelative) init() {
	m.data.SetName("ambientweather.pressure.relative")
	m.data.SetDescription("Relative (sea-level-adjusted) barometric pressure.")
	m.data.SetUnit("hPa")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherPressureRelative) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherPressureRelative) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherPressureRelative) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherPressureRelative(cfg AmbientweatherPressureRelativeMetricConfig) metricAmbientweatherPressureRelative {
	m := metricAmbientweatherPressureRelative{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherRainRate struct {
	data     pmetric.Metric                     // data buffer for generated metric.
	config   AmbientweatherRainRateMetricConfig // metric config provided by user.
	capacity int                                // max observed number of data points added to the metric.
}

// init fills ambientweather.rain.rate metric with initial data.
func (m *metricAmbientweatherRainRate) init() {
	m.data.SetName("ambientweather.rain.rate")
	m.data.SetDescription("Instantaneous rain rate.")
	m.data.SetUnit("mm/h")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherRainRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherRainRate) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherRainRate) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherRainRate(cfg AmbientweatherRainRateMetricConfig) metricAmbientweatherRainRate {
	m := metricAmbientweatherRainRate{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherRainfall struct {
	data          pmetric.Metric                     // data buffer for generated metric.
	config        AmbientweatherRainfallMetricConfig // metric config provided by user.
	capacity      int                                // max observed number of data points added to the metric.
	aggDataPoints []float64                          // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.rainfall metric with initial data.
func (m *metricAmbientweatherRainfall) init() {
	m.data.SetName("ambientweather.rainfall")
	m.data.SetDescription("Accumulated rainfall over the reported period.")
	m.data.SetUnit("mm")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherRainfall) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, rainfallPeriodAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherRainfallMetricAttributeKeyRainfallPeriod) {
		dp.Attributes().PutStr("rainfall.period", rainfallPeriodAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherRainfall) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherRainfall) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherRainfall(cfg AmbientweatherRainfallMetricConfig) metricAmbientweatherRainfall {
	m := metricAmbientweatherRainfall{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherSoilMoisture struct {
	data          pmetric.Metric                         // data buffer for generated metric.
	config        AmbientweatherSoilMoistureMetricConfig // metric config provided by user.
	capacity      int                                    // max observed number of data points added to the metric.
	aggDataPoints []float64                              // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.soil.moisture metric with initial data.
func (m *metricAmbientweatherSoilMoisture) init() {
	m.data.SetName("ambientweather.soil.moisture")
	m.data.SetDescription("Soil moisture.")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherSoilMoisture) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherSoilMoistureMetricAttributeKeySensor) {
		dp.Attributes().PutStr("sensor", sensorAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherSoilMoisture) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherSoilMoisture) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherSoilMoisture(cfg AmbientweatherSoilMoistureMetricConfig) metricAmbientweatherSoilMoisture {
	m := metricAmbientweatherSoilMoisture{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherSolarRadiation struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   AmbientweatherSolarRadiationMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills ambientweather.solar.radiation metric with initial data.
func (m *metricAmbientweatherSolarRadiation) init() {
	m.data.SetName("ambientweather.solar.radiation")
	m.data.SetDescription("Solar irradiance.")
	m.data.SetUnit("W/m2")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherSolarRadiation) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherSolarRadiation) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherSolarRadiation) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherSolarRadiation(cfg AmbientweatherSolarRadiationMetricConfig) metricAmbientweatherSolarRadiation {
	m := metricAmbientweatherSolarRadiation{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherTemperature struct {
	data          pmetric.Metric                        // data buffer for generated metric.
	config        AmbientweatherTemperatureMetricConfig // metric config provided by user.
	capacity      int                                   // max observed number of data points added to the metric.
	aggDataPoints []float64                             // slice containing number of aggregated datapoints at each index
}

// init fills ambientweather.temperature metric with initial data.
func (m *metricAmbientweatherTemperature) init() {
	m.data.SetName("ambientweather.temperature")
	m.data.SetDescription("Air temperature reading.")
	m.data.SetUnit("Cel")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAmbientweatherTemperature) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, AmbientweatherTemperatureMetricAttributeKeySensor) {
		dp.Attributes().PutStr("sensor", sensorAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherTemperature) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherTemperature) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherTemperature(cfg AmbientweatherTemperatureMetricConfig) metricAmbientweatherTemperature {
	m := metricAmbientweatherTemperature{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherUvIndex struct {
	data     pmetric.Metric                    // data buffer for generated metric.
	config   AmbientweatherUvIndexMetricConfig // metric config provided by user.
	capacity int                               // max observed number of data points added to the metric.
}

// init fills ambientweather.uv.index metric with initial data.
func (m *metricAmbientweatherUvIndex) init() {
	m.data.SetName("ambientweather.uv.index")
	m.data.SetDescription("Ultraviolet radiation index.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherUvIndex) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherUvIndex) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherUvIndex) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherUvIndex(cfg AmbientweatherUvIndexMetricConfig) metricAmbientweatherUvIndex {
	m := metricAmbientweatherUvIndex{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherWindDirection struct {
	data     pmetric.Metric                          // data buffer for generated metric.
	config   AmbientweatherWindDirectionMetricConfig // metric config provided by user.
	capacity int                                     // max observed number of data points added to the metric.
}

// init fills ambientweather.wind.direction metric with initial data.
func (m *metricAmbientweatherWindDirection) init() {
	m.data.SetName("ambientweather.wind.direction")
	m.data.SetDescription("Wind direction, in degrees clockwise from true north.")
	m.data.SetUnit("deg")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherWindDirection) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherWindDirection) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherWindDirection) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherWindDirection(cfg AmbientweatherWindDirectionMetricConfig) metricAmbientweatherWindDirection {
	m := metricAmbientweatherWindDirection{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherWindGust struct {
	data     pmetric.Metric                     // data buffer for generated metric.
	config   AmbientweatherWindGustMetricConfig // metric config provided by user.
	capacity int                                // max observed number of data points added to the metric.
}

// init fills ambientweather.wind.gust metric with initial data.
func (m *metricAmbientweatherWindGust) init() {
	m.data.SetName("ambientweather.wind.gust")
	m.data.SetDescription("Instantaneous wind gust speed.")
	m.data.SetUnit("m/s")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherWindGust) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherWindGust) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherWindGust) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherWindGust(cfg AmbientweatherWindGustMetricConfig) metricAmbientweatherWindGust {
	m := metricAmbientweatherWindGust{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricAmbientweatherWindSpeed struct {
	data     pmetric.Metric                      // data buffer for generated metric.
	config   AmbientweatherWindSpeedMetricConfig // metric config provided by user.
	capacity int                                 // max observed number of data points added to the metric.
}

// init fills ambientweather.wind.speed metric with initial data.
func (m *metricAmbientweatherWindSpeed) init() {
	m.data.SetName("ambientweather.wind.speed")
	m.data.SetDescription("Instantaneous wind speed.")
	m.data.SetUnit("m/s")
	m.data.SetEmptyGauge()
}

func (m *metricAmbientweatherWindSpeed) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAmbientweatherWindSpeed) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAmbientweatherWindSpeed) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricAmbientweatherWindSpeed(cfg AmbientweatherWindSpeedMetricConfig) metricAmbientweatherWindSpeed {
	m := metricAmbientweatherWindSpeed{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                MetricsBuilderConfig // config of the metrics builder.
	startTime                             pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                       int                  // maximum observed number of metrics per resource.
	metricsBuffer                         pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                             component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter        map[string]filter.Filter
	resourceAttributeExcludeFilter        map[string]filter.Filter
	metricAmbientweatherBatteryStatus     metricAmbientweatherBatteryStatus
	metricAmbientweatherHumidity          metricAmbientweatherHumidity
	metricAmbientweatherLightningDistance metricAmbientweatherLightningDistance
	metricAmbientweatherLightningStrikes  metricAmbientweatherLightningStrikes
	metricAmbientweatherPm25              metricAmbientweatherPm25
	metricAmbientweatherPressureAbsolute  metricAmbientweatherPressureAbsolute
	metricAmbientweatherPressureRelative  metricAmbientweatherPressureRelative
	metricAmbientweatherRainRate          metricAmbientweatherRainRate
	metricAmbientweatherRainfall          metricAmbientweatherRainfall
	metricAmbientweatherSoilMoisture      metricAmbientweatherSoilMoisture
	metricAmbientweatherSolarRadiation    metricAmbientweatherSolarRadiation
	metricAmbientweatherTemperature       metricAmbientweatherTemperature
	metricAmbientweatherUvIndex           metricAmbientweatherUvIndex
	metricAmbientweatherWindDirection     metricAmbientweatherWindDirection
	metricAmbientweatherWindGust          metricAmbientweatherWindGust
	metricAmbientweatherWindSpeed         metricAmbientweatherWindSpeed
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                mbc,
		startTime:                             pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                         pmetric.NewMetrics(),
		buildInfo:                             settings.BuildInfo,
		metricAmbientweatherBatteryStatus:     newMetricAmbientweatherBatteryStatus(mbc.Metrics.AmbientweatherBatteryStatus),
		metricAmbientweatherHumidity:          newMetricAmbientweatherHumidity(mbc.Metrics.AmbientweatherHumidity),
		metricAmbientweatherLightningDistance: newMetricAmbientweatherLightningDistance(mbc.Metrics.AmbientweatherLightningDistance),
		metricAmbientweatherLightningStrikes:  newMetricAmbientweatherLightningStrikes(mbc.Metrics.AmbientweatherLightningStrikes),
		metricAmbientweatherPm25:              newMetricAmbientweatherPm25(mbc.Metrics.AmbientweatherPm25),
		metricAmbientweatherPressureAbsolute:  newMetricAmbientweatherPressureAbsolute(mbc.Metrics.AmbientweatherPressureAbsolute),
		metricAmbientweatherPressureRelative:  newMetricAmbientweatherPressureRelative(mbc.Metrics.AmbientweatherPressureRelative),
		metricAmbientweatherRainRate:          newMetricAmbientweatherRainRate(mbc.Metrics.AmbientweatherRainRate),
		metricAmbientweatherRainfall:          newMetricAmbientweatherRainfall(mbc.Metrics.AmbientweatherRainfall),
		metricAmbientweatherSoilMoisture:      newMetricAmbientweatherSoilMoisture(mbc.Metrics.AmbientweatherSoilMoisture),
		metricAmbientweatherSolarRadiation:    newMetricAmbientweatherSolarRadiation(mbc.Metrics.AmbientweatherSolarRadiation),
		metricAmbientweatherTemperature:       newMetricAmbientweatherTemperature(mbc.Metrics.AmbientweatherTemperature),
		metricAmbientweatherUvIndex:           newMetricAmbientweatherUvIndex(mbc.Metrics.AmbientweatherUvIndex),
		metricAmbientweatherWindDirection:     newMetricAmbientweatherWindDirection(mbc.Metrics.AmbientweatherWindDirection),
		metricAmbientweatherWindGust:          newMetricAmbientweatherWindGust(mbc.Metrics.AmbientweatherWindGust),
		metricAmbientweatherWindSpeed:         newMetricAmbientweatherWindSpeed(mbc.Metrics.AmbientweatherWindSpeed),
		resourceAttributeIncludeFilter:        make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:        make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.AmbientweatherStationMac.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ambientweather.station.mac"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationMac.MetricsInclude)
	}
	if mbc.ResourceAttributes.AmbientweatherStationMac.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ambientweather.station.mac"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationMac.MetricsExclude)
	}
	if mbc.ResourceAttributes.AmbientweatherStationName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ambientweather.station.name"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationName.MetricsInclude)
	}
	if mbc.ResourceAttributes.AmbientweatherStationName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ambientweather.station.name"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationName.MetricsExclude)
	}
	if mbc.ResourceAttributes.AmbientweatherStationType.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ambientweather.station.type"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationType.MetricsInclude)
	}
	if mbc.ResourceAttributes.AmbientweatherStationType.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ambientweather.station.type"] = filter.CreateFilter(mbc.ResourceAttributes.AmbientweatherStationType.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricAmbientweatherBatteryStatus.emit(ils.Metrics())
	mb.metricAmbientweatherHumidity.emit(ils.Metrics())
	mb.metricAmbientweatherLightningDistance.emit(ils.Metrics())
	mb.metricAmbientweatherLightningStrikes.emit(ils.Metrics())
	mb.metricAmbientweatherPm25.emit(ils.Metrics())
	mb.metricAmbientweatherPressureAbsolute.emit(ils.Metrics())
	mb.metricAmbientweatherPressureRelative.emit(ils.Metrics())
	mb.metricAmbientweatherRainRate.emit(ils.Metrics())
	mb.metricAmbientweatherRainfall.emit(ils.Metrics())
	mb.metricAmbientweatherSoilMoisture.emit(ils.Metrics())
	mb.metricAmbientweatherSolarRadiation.emit(ils.Metrics())
	mb.metricAmbientweatherTemperature.emit(ils.Metrics())
	mb.metricAmbientweatherUvIndex.emit(ils.Metrics())
	mb.metricAmbientweatherWindDirection.emit(ils.Metrics())
	mb.metricAmbientweatherWindGust.emit(ils.Metrics())
	mb.metricAmbientweatherWindSpeed.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordAmbientweatherBatteryStatusDataPoint adds a data point to ambientweather.battery.status metric.
func (mb *MetricsBuilder) RecordAmbientweatherBatteryStatusDataPoint(ts pcommon.Timestamp, val int64, sensorAttributeValue string) {
	mb.metricAmbientweatherBatteryStatus.recordDataPoint(mb.startTime, ts, val, sensorAttributeValue)
}

// RecordAmbientweatherHumidityDataPoint adds a data point to ambientweather.humidity metric.
func (mb *MetricsBuilder) RecordAmbientweatherHumidityDataPoint(ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	mb.metricAmbientweatherHumidity.recordDataPoint(mb.startTime, ts, val, sensorAttributeValue)
}

// RecordAmbientweatherLightningDistanceDataPoint adds a data point to ambientweather.lightning.distance metric.
func (mb *MetricsBuilder) RecordAmbientweatherLightningDistanceDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherLightningDistance.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherLightningStrikesDataPoint adds a data point to ambientweather.lightning.strikes metric.
func (mb *MetricsBuilder) RecordAmbientweatherLightningStrikesDataPoint(ts pcommon.Timestamp, val int64, lightningPeriodAttributeValue string) {
	mb.metricAmbientweatherLightningStrikes.recordDataPoint(mb.startTime, ts, val, lightningPeriodAttributeValue)
}

// RecordAmbientweatherPm25DataPoint adds a data point to ambientweather.pm25 metric.
func (mb *MetricsBuilder) RecordAmbientweatherPm25DataPoint(ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	mb.metricAmbientweatherPm25.recordDataPoint(mb.startTime, ts, val, sensorAttributeValue)
}

// RecordAmbientweatherPressureAbsoluteDataPoint adds a data point to ambientweather.pressure.absolute metric.
func (mb *MetricsBuilder) RecordAmbientweatherPressureAbsoluteDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherPressureAbsolute.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherPressureRelativeDataPoint adds a data point to ambientweather.pressure.relative metric.
func (mb *MetricsBuilder) RecordAmbientweatherPressureRelativeDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherPressureRelative.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherRainRateDataPoint adds a data point to ambientweather.rain.rate metric.
func (mb *MetricsBuilder) RecordAmbientweatherRainRateDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherRainRate.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherRainfallDataPoint adds a data point to ambientweather.rainfall metric.
func (mb *MetricsBuilder) RecordAmbientweatherRainfallDataPoint(ts pcommon.Timestamp, val float64, rainfallPeriodAttributeValue string) {
	mb.metricAmbientweatherRainfall.recordDataPoint(mb.startTime, ts, val, rainfallPeriodAttributeValue)
}

// RecordAmbientweatherSoilMoistureDataPoint adds a data point to ambientweather.soil.moisture metric.
func (mb *MetricsBuilder) RecordAmbientweatherSoilMoistureDataPoint(ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	mb.metricAmbientweatherSoilMoisture.recordDataPoint(mb.startTime, ts, val, sensorAttributeValue)
}

// RecordAmbientweatherSolarRadiationDataPoint adds a data point to ambientweather.solar.radiation metric.
func (mb *MetricsBuilder) RecordAmbientweatherSolarRadiationDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherSolarRadiation.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherTemperatureDataPoint adds a data point to ambientweather.temperature metric.
func (mb *MetricsBuilder) RecordAmbientweatherTemperatureDataPoint(ts pcommon.Timestamp, val float64, sensorAttributeValue string) {
	mb.metricAmbientweatherTemperature.recordDataPoint(mb.startTime, ts, val, sensorAttributeValue)
}

// RecordAmbientweatherUvIndexDataPoint adds a data point to ambientweather.uv.index metric.
func (mb *MetricsBuilder) RecordAmbientweatherUvIndexDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricAmbientweatherUvIndex.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherWindDirectionDataPoint adds a data point to ambientweather.wind.direction metric.
func (mb *MetricsBuilder) RecordAmbientweatherWindDirectionDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherWindDirection.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherWindGustDataPoint adds a data point to ambientweather.wind.gust metric.
func (mb *MetricsBuilder) RecordAmbientweatherWindGustDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherWindGust.recordDataPoint(mb.startTime, ts, val)
}

// RecordAmbientweatherWindSpeedDataPoint adds a data point to ambientweather.wind.speed metric.
func (mb *MetricsBuilder) RecordAmbientweatherWindSpeedDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricAmbientweatherWindSpeed.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
